POST http://localhost:3000/register/add
Content-Type: application/json

{
    "first_name" : "dummy",
    "email" : "sebuahemail@domain.com",
    "password": "sebuahPassword"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "email": "sebuahemail@domain.com",
    "password": "sebuahPassword"
}